### PR TITLE
Add EPG icon in PVR Guide Info

### PR DESCRIPTION
**Pull request by ludovik35**
Hello,
I'd to introduce you a small improvement to had EPG Icon in the PVR.
I hope you would like it ;-)
Ludovik

### CODE REVIEW

**Comment by heppen-dev** [comment]
Hey, could you please add some screenshots?

**Comment by ludovik35** [comment]
No problem, 

Here is one screenshot

Kodi_20220414_234542

**Comment by heppen-dev** [comment]
Awesome, thanks. Merged :)

**Comment by heppen-dev** [comment]
Update should be already in heppen's repository :)

**Pull request merged**
